#EJERCICIO1 SE COMPARA LAS FRASES "DIOS VIVE" "CHISTO TIENE PODER"
print("DIOS VIVE"!="CHISTO TIENE PODER")
#EJERCICIO2 SE COMPARA LAS FRASES "MARCIANO" "CHUPETE"
print("MARCIANO"<"CHUPETE")
#EJERCICIO3 SE COMPARA LAS FRASES "SILLA" "CARPETA"
print("SILLA">"CARPETA")
#EJERCICIO4 SE COMPARA LAS FRASES "ESCOLEOSIS" "ARTRITIS"
print("ESCOLEOSIS"!="ARTRITIS")
#EJERCICIO5SE COMPARA LAS FRASES "CATRIANA" "ANDALUCIA"
print("CATRIANA">"ANDALUCIA")
#EJERCICIO6 SE COMPARRA LAS FRASES "HOLA MUNDO" "TRRICOLA VIVIENTE"
print("HOLA MUNDO"== "TERRICOLA VIVIENTE")
#EJERCICIO7 SE COMPARRA LAS FRASES "cocoddrilo" y "rinoceronte"
print("cocoddrilo" < "rinoceronte")
#EJERCICIO8 SE COMPARA LAS FRASES "MOTOCICLETA" "RECORRIDO"
print("MOTOCICLETA">"RECORRIDO")
#EJERCICIO9 SE COMPARA LAS FRASES "CALCULADOR" "ANDROI"
print("CALCULADOR"=="ANDROI")
#EJERCICIO10 SE COMPARA LAS FRASES "ARACNIDO" "MAMIFERO"
print("ARACNIDO"!="MAMIFERO")
#EJERCICIO11 SE COMPARA LAS FRASES "ESTERNOCLEIDO" "MASTOIDEO"
print("ESTERNOCLEIDO"<="MASTOIDEO")
#EJERCICIO12 SE COMPARA LAS FRASES "RADIO" "TELESCOPIO"
print("RADIO">="TELESCOPIO")
#EJERCICIO13 SE COMPARA LAS FRASES "CARLOS" "MIGUEL"
print("CARLOS">"MIGUEL")
#EJERCICIO14 SE COMPARA LAS FRASES "MARSUPIAL" "ORNITORRINCO"
print("MARSUPIAL"=="ORNITORRINCO")
#EJERCICIO15 SE COMPARA LAS FRASES "LAGARTIJA" "COCODRILO"
print("LAGARTIJA"!="COCODRILO")


